# Site settings
title: Santiago Camelo
email: trikanna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's learn new Front End Skills. Free resources. Website and Blog talking about real life Front End Engineering tips and tricks. Tutorials and Video Lessons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.trikanna.com/" # the base hostname & protocol for your site, e.g. http://example.com
enable_retina: true
permalink: :title

nav_list:
  Home : ['Home', '/', 'fa-home']
  Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
  Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/michelle', 'fa-user']

single_footer: '<p>The writer community loves your content. Writer &copy; 2016 <a href="/">latest posts</a></p>'

footer_links:
    About: ['About', '/about']
    Writer: ['Santiago Camelo 2017', '/about']

twitter_username: trikanna
github_username:  trikanna

# Build settings
markdown: kramdown

#gems:
#  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock